title: Marked
email: wm@mengw.io
description: Marked
url: https://marked.sudo.dog
github_username: WMXPY
theme: minima
repository: SudoDotDog/marked.sudo.dog
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
author:
  name: WMXPY
  email: wm@mengw.io
plugins:
  - jekyll-github-metadata
exclude:
  - .jekyll-cache/
  - docs/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - makefile
